apiVersion: secrets.platform.io/v1alpha1
kind: SecretContract
metadata:
  labels:
    app.kubernetes.io/name: secret-contract-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretcontract-sample
spec:
  # TODO(user): Add fields here
