//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretContractStatus) DeepCopyInto(out *ExternalSecretContractStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretContractStatus.
func (in *ExternalSecretContractStatus) DeepCopy() *ExternalSecretContractStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalSecretReference) DeepCopyInto(out *ExternalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalSecretReference.
func (in *ExternalSecretReference) DeepCopy() *ExternalSecretReference {
	if in == nil {
		return nil
	}
	out := new(ExternalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InjectionPolicy) DeepCopyInto(out *InjectionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InjectionPolicy.
func (in *InjectionPolicy) DeepCopy() *InjectionPolicy {
	if in == nil {
		return nil
	}
	out := new(InjectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicy) DeepCopyInto(out *RotationPolicy) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicy.
func (in *RotationPolicy) DeepCopy() *RotationPolicy {
	if in == nil {
		return nil
	}
	out := new(RotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretContract) DeepCopyInto(out *SecretContract) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretContract.
func (in *SecretContract) DeepCopy() *SecretContract {
	if in == nil {
		return nil
	}
	out := new(SecretContract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretContract) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretContractList) DeepCopyInto(out *SecretContractList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretContract, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretContractList.
func (in *SecretContractList) DeepCopy() *SecretContractList {
	if in == nil {
		return nil
	}
	out := new(SecretContractList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretContractList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretContractPolicy) DeepCopyInto(out *SecretContractPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretContractPolicy.
func (in *SecretContractPolicy) DeepCopy() *SecretContractPolicy {
	if in == nil {
		return nil
	}
	out := new(SecretContractPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretContractSpec) DeepCopyInto(out *SecretContractSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.RequiredKeys != nil {
		in, out := &in.RequiredKeys, &out.RequiredKeys
		*out = make([]SecretKeyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalSecretRef != nil {
		in, out := &in.ExternalSecretRef, &out.ExternalSecretRef
		*out = new(ExternalSecretReference)
		**out = **in
	}
	if in.WorkloadRefs != nil {
		in, out := &in.WorkloadRefs, &out.WorkloadRefs
		*out = make([]WorkloadReference, len(*in))
		copy(*out, *in)
	}
	if in.Injection != nil {
		in, out := &in.Injection, &out.Injection
		*out = new(InjectionPolicy)
		**out = **in
	}
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(RotationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(SecretContractPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretContractSpec.
func (in *SecretContractSpec) DeepCopy() *SecretContractSpec {
	if in == nil {
		return nil
	}
	out := new(SecretContractSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretContractStatus) DeepCopyInto(out *SecretContractStatus) {
	*out = *in
	if in.MissingKeys != nil {
		in, out := &in.MissingKeys, &out.MissingKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Violations != nil {
		in, out := &in.Violations, &out.Violations
		*out = make([]SecretContractViolation, len(*in))
		copy(*out, *in)
	}
	if in.ExternalSecretStatus != nil {
		in, out := &in.ExternalSecretStatus, &out.ExternalSecretStatus
		*out = new(ExternalSecretContractStatus)
		**out = **in
	}
	if in.WorkloadStatuses != nil {
		in, out := &in.WorkloadStatuses, &out.WorkloadStatuses
		*out = make([]WorkloadContractStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastCheckedTime != nil {
		in, out := &in.LastCheckedTime, &out.LastCheckedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretContractStatus.
func (in *SecretContractStatus) DeepCopy() *SecretContractStatus {
	if in == nil {
		return nil
	}
	out := new(SecretContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretContractViolation) DeepCopyInto(out *SecretContractViolation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretContractViolation.
func (in *SecretContractViolation) DeepCopy() *SecretContractViolation {
	if in == nil {
		return nil
	}
	out := new(SecretContractViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRule) DeepCopyInto(out *SecretKeyRule) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.NonEmpty != nil {
		in, out := &in.NonEmpty, &out.NonEmpty
		*out = new(bool)
		**out = **in
	}
	if in.MinLength != nil {
		in, out := &in.MinLength, &out.MinLength
		*out = new(int32)
		**out = **in
	}
	if in.MaxLength != nil {
		in, out := &in.MaxLength, &out.MaxLength
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRule.
func (in *SecretKeyRule) DeepCopy() *SecretKeyRule {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadContractStatus) DeepCopyInto(out *WorkloadContractStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadContractStatus.
func (in *WorkloadContractStatus) DeepCopy() *WorkloadContractStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadContractStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
